version: '3.1'
services:
  test-db:
    image: postgres:16
    container_name: test-database-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: final_soft
    ports:
      - "2346:5432"
    tmpfs:
      - /var/lib/postgresql/data